In [3]:
# 準備一個測試的矩陣, 你可以當成三筆資料(兩個欄位)
import numpy as np
X = np.array([[1, 4, 5], 
        [4, 2, 8], 
        [5, 8, 3]])
X

array([[1, 4, 5],
       [4, 2, 8],
       [5, 8, 3]])

In [4]:
# 先使用sklearn的PCA來看一下轉換的成果, 變成三筆資料(兩個欄位)
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
X_pca

array([[-0.80537496,  2.31330309],
       [-3.51815346, -1.51303103],
       [ 4.32352842, -0.80027206]])

In [5]:
# 新的正交座標軸
pca.components_

array([[ 0.21248047,  0.76706308, -0.60536458],
       [-0.93468378, -0.0211357 , -0.35485139]])

In [8]:
# 我們自己來試一次, 記得要把平均移到0
# 先求Conv
newX = X - X.mean(axis=0)
COV = np.cov(newX.T)
COV

array([[ 4.33333333,  2.66666667, -0.66666667],
       [ 2.66666667,  9.33333333, -7.33333333],
       [-0.66666667, -7.33333333,  6.33333333]])

In [9]:
# 使用特徵值分解分解成三個矩陣, 我把順序換得跟講義一樣
from numpy import linalg as LA
W, V = LA.eig(COV)
Q_T, A, Q = V, np.diag(W), V.T

In [11]:
# 你可以看到三個東西相乘起來就是我們的 COV
Q_T.dot(A).dot(Q)

array([[ 4.33333333,  2.66666667, -0.66666667],
       [ 2.66666667,  9.33333333, -7.33333333],
       [-0.66666667, -7.33333333,  6.33333333]])

In [16]:
# 利用係數取最大的兩個值, 你可以看到得到的兩個軸和sklearn得到的基本上是一樣的(只是方向相反而已)
wq_pair = sorted(zip(W, Q), key=lambda x:x[0], reverse=True)
Q_fil = np.array([v for w, v in wq_pair[:2]])
Q_fil

array([[-0.21248047, -0.76706308,  0.60536458],
       [-0.93468378, -0.0211357 , -0.35485139]])

In [19]:
# 兩個軸是否正交
Q_fil[0].dot(Q_fil[1])

-3.0531133177191805e-16

In [17]:
# 轉換過後得到的值
Q_fil.dot(newX.T).T

array([[ 0.80537496,  2.31330309],
       [ 3.51815346, -1.51303103],
       [-4.32352842, -0.80027206]])